project:
  metadata:
    key: fineract-site
    committee: fineract
    name: Apache Fineract project website
publish:
  whoami: asf-site
notifications:
  commits: commits@fineract.apache.org
  pullrequests: issues@fineract.apache.org
github:
  description: 🌐 Apache Fineract project website
  features:
    issues: true
  enabled_merge_buttons:
    merge: true
    squash: false
    rebase: false
  rulesets:
    - name: "Branch Protection"
      type: branch
      branches:
        includes:
          - "asf-site"
      restrict_deletion: true
      restrict_force_push: true
      required_signatures: false
      required_linear_history: false
