publish:
  whoami: asf-site
notifications:
  commits: commits@fineract.apache.org
  pullrequests: issues@fineract.apache.org
github:
  enabled_merge_buttons:
    merge: true
    squash: false
    rebase: false
  protected_branches:
    asf-site:
      required_linear_history: false
      required_conversation_resolution: true
      required_signatures: false
