baseURL = "https://fineract.apache.org/"
languageCode = "en-us"
title = "Apache Fineract®"

disableKinds = ["taxonomy", "term"]
disableHugoGeneratorInject = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 2

[module]
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "../docs"
    target = "static/docs"
  [[module.mounts]]
    source = "../.htaccess"
    target = "static/.htaccess"
  [[module.mounts]]
    source = "../doap_Fineract.rdf"
    target = "static/doap_Fineract.rdf"
  [[module.mounts]]
    source = "../css"
    target = "static/css"
  [[module.mounts]]
    source = "../js"
    target = "static/js"
  [[module.mounts]]
    source = "../images"
    target = "static/images"
  [[module.mounts]]
    source = "../font"
    target = "static/font"
